# Generated by Django 5.2.1 on 2025-05-24 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0003_researchresult_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.researchresult')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qanda_set', to='chat.chat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['-created_at'], name='chat_chat_created_fa771b_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-created_at'], name='chat_chat_user_id_d9308c_idx'),
        ),
        migrations.AddIndex(
            model_name='qanda',
            index=models.Index(fields=['-created_at'], name='chat_qanda_created_dbba44_idx'),
        ),
        migrations.AddIndex(
            model_name='qanda',
            index=models.Index(fields=['chat', '-created_at'], name='chat_qanda_chat_id_7b3141_idx'),
        ),
    ]
