# Generated by Django 5.2.1 on 2025-06-06 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0007_alter_politician_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianPicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politicians', models.ManyToManyField(related_name='picked_by_users', to='research.politician')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='politician_picks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Politician picks',
            },
        ),
    ]
