# Generated by Django 5.2.1 on 2025-05-19 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('party', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='research_po_name_73c36b_idx'), models.Index(fields=['position'], name='research_po_positio_790abb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.TextField(blank=True)),
                ('accomplishments', models.TextField(blank=True)),
                ('criticisms', models.TextField(blank=True)),
                ('sources', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_results', to='research.politician')),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='research_re_created_c86d45_idx'), models.Index(fields=['politician', '-created_at'], name='research_re_politic_e21378_idx')],
            },
        ),
    ]
