# Generated by Django 5.2.1 on 2025-05-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_remove_politician_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresult',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
