# Generated by Django 5.2.1 on 2025-05-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchresult_summary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='politician',
            name='research_po_positio_790abb_idx',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='position',
        ),
        migrations.AddField(
            model_name='researchresult',
            name='position',
            field=models.CharField(default='Politician', max_length=200),
        ),
        migrations.AddIndex(
            model_name='researchresult',
            index=models.Index(fields=['position'], name='research_re_positio_befa3d_idx'),
        ),
    ]
