# Generated by Django 5.2.1 on 2025-05-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_researchresult_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresult',
            name='image_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
