# Generated by Django 5.2.1 on 2025-05-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_researchresult_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='issues',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='politician',
            name='party',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
